name: Deploy React App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node environment
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          
          # Clean existing setup
          rm -rf node_modules package-lock.json
      
      - name: Install all dependencies
        run: |
          cd /home/karan-connect/actions-runner/_work/VAC/VAC
          # First try with clean install
          npm ci || npm install --production=false --legacy-peer-deps
        
      - name: Verify installation
        run: |
          cd /home/karan-connect/actions-runner/_work/VAC/VAC
          echo "Checking node_modules:"
          ls -la node_modules
          echo "Installed dependencies:"
          npm list --depth=0
          
      - name: Build application
        run: |
          cd /home/karan-connect/actions-runner/_work/VAC/VAC
          export NODE_OPTIONS=--max_old_space_size=4096
          CI=false npm run build
        
      - name: Show Error Logs if Failed
        if: failure()
        run: |
          echo "Latest NPM log:"
          cat $(ls -t /home/karan-connect/.npm/_logs/*.log | head -1)
