name: Deploy React App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # This runs on your server directly
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies and build
        run: |
          # Print working directory for verification
          pwd
          echo "Current directory contents:"
          ls -la
          
          # Install dependencies
          npm ci || npm install --production=false --legacy-peer-deps
          
          # Build the application
          export NODE_OPTIONS=--max_old_space_size=4096
          CI=false npm run build
          
      - name: Verify build
        run: |
          echo "Build directory contents:"
          ls -la build/
          
      - name: Show Error Logs if Failed
        if: failure()
        run: |
          echo "Latest NPM log:"
          cat $(ls -t /home/karan-connect/.npm/_logs/*.log | head -1)
