name: Deploy React App

on:
  push:
    branches: [ master ]  # or your default branch name
  workflow_dispatch:    # allows manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # This uses your newly configured runner
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags
      
      - name: Update and build application
        run: |
          # Navigate to your React app directory - MODIFY THIS PATH
          cd /home/karan-connect/ml-loader
          
          # Fetch latest changes
          git fetch origin
          
          # Reset to match remote branch
          git reset --hard origin/master
          
          # Install dependencies
          npm install
          
          # Build the application
          #npm run build

      - name: Check deployment status
        run: |
          echo "Deployment completed"
          npm list
