name: Sync React Dev Environment

on:
  push:
    branches: [ master ]  # or your default branch
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    
    steps:
      - name: Pull latest changes
        run: |
          cd /home/karan-connect/ml-loader  # Update this to your React app directory
          git pull origin master
          
      - name: Update dependencies
        run: |
          cd /home/karan-connect/ml-loader # Update this to your React app directory
          npm install

      - name: Verify sync
        run: |
          cd /home/karan-connect/VAC
          echo "Current git commit:"
          git rev-parse HEAD
          echo "Dependencies installed:"
          npm list --depth=0
