name: Sync React Dev Environment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dependencies in Actions workspace
        run: |
          cd /home/karan-connect/actions-runner/_work/VAC/VAC
          npm install
          
      - name: Sync with development directory
        run: |
          # Create ml-loader directory if it doesn't exist
          mkdir -p /home/karan-connect/ml-loader
          
          # Copy all files except node_modules
          rsync -av --exclude='node_modules' /home/karan-connect/actions-runner/_work/VAC/VAC/ /home/karan-connect/ml-loader/
          
          # Install dependencies in the dev directory
          cd /home/karan-connect/ml-loader
          npm install

      - name: Verify sync
        run: |
          echo "Development directory contents:"
          ls -la /home/karan-connect/ml-loader
